/* UniGuard · PDF exports (js/pdf.js)
 *
 * ONE shared helper that produces every export in the system. All exports are
 * formatted PDFs — there is no CSV, JSON or raw-text export anywhere.
 *
 * Uses the vendored copies of jsPDF and jspdf-autotable (vendor/, precached by
 * sw.js — no CDN at runtime). Every document carries:
 *   · a title and subtitle
 *   · generated date/time
 *   · generated-by (name and role)
 *   · the data scope (which barangay, or municipality-wide)
 *   · tables with repeating headers
 *   · "Page X of Y" page numbers
 */
const UG_PDF = (function () {
  function ready() {
    return typeof window !== 'undefined' &&
      window.jspdf && window.jspdf.jsPDF &&
      typeof window.jspdf.jsPDF.API !== 'undefined' &&
      typeof window.jspdf.jsPDF.API.autoTable === 'function';
  }

  function noteIfMissing() {
    if (!ready()) throw new Error('The PDF engine has not loaded yet. Check your connection and retry.');
  }

  /* docHeader / docFooter draw on every page via didDrawPage */
  function exportDoc(opts) {
    noteIfMissing();
    const jsPDF = window.jspdf.jsPDF;
    const doc = new jsPDF({ orientation: opts.landscape ? 'landscape' : 'portrait', unit: 'pt', format: 'a4' });
    const W = doc.internal.pageSize.getWidth();
    const H = doc.internal.pageSize.getHeight();
    const M = 40;

    const brand = (o) => {
      doc.setFillColor(5, 9, 16);
      doc.rect(0, 0, W, 64, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('UniGuard', M, 28);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(163, 182, 208);
      doc.text('Unified Disaster Risk Reduction and Management System · ' + (o.place || 'Lingayen, Pangasinan'), M, 44);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      const kind = opts.kind || 'Report';
      doc.text(String(kind).toUpperCase(), W - M, 28, { align: 'right' });
    };

    const head = (o) => {
      o = o || opts;
      brand(o);
      let y = 92;
      doc.setTextColor(11, 18, 32);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.text(String(opts.title || 'Export'), M, y); y += 18;
      if (opts.subtitle) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(90, 105, 130);
        doc.text(String(opts.subtitle), M, y); y += 14;
      }
      doc.setFontSize(8.5);
      doc.setTextColor(90, 105, 130);
      const meta = [
        'Generated: ' + new Date().toLocaleString(),
        'Generated by: ' + (opts.generatedBy || 'UniGuard'),
        'Scope: ' + (opts.scope || 'Municipality-wide')
      ];
      meta.forEach((m) => { doc.text(m, M, y); y += 11.5; });
      if (opts.meta) {
        String(opts.meta).split('\n').forEach((m) => { if (m) { doc.text(m, M, y); y += 11.5; } });
      }
      return y + 8;
    };

    const drawFooter = () => {
      const pages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pages; i++) {
        doc.setPage(i);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(120, 134, 156);
        doc.text('Page ' + i + ' of ' + pages, W - M, H - 18, { align: 'right' });
        doc.text('UniGuard · generated ' + new Date().toLocaleString(), M, H - 18);
      }
    };

    let startY = head();

    (opts.tables || []).forEach((t, idx) => {
      if (idx > 0) startY = head();
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(11, 18, 32);
      doc.text(String(t.name || ''), M, startY + 6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(110, 124, 148);
      if (t.note) {
        const lines = doc.splitTextToSize(String(t.note), W - M * 2);
        doc.text(lines, M, startY + 18);
        startY += lines.length * 10.5;
      }
      doc.autoTable({
        startY: startY + 22,
        head: [t.head || []],
        body: t.rows || [],
        styles: { fontSize: 8, cellPadding: 4, textColor: [30, 41, 59], lineColor: [226, 232, 240], lineWidth: 0.5 },
        headStyles: { fillColor: [12, 21, 36], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [246, 249, 253] },
        margin: { left: M, right: M },
        didDrawPage: () => { brand(opts); },
        showHead: 'everyPage'
      });
      if (idx < opts.tables.length - 1) {
        doc.addPage(opts.landscape ? 'landscape' : 'portrait');
      }
    });

    drawFooter();
    doc.save(opts.filename || 'uniguard-export.pdf');
    return true;
  }

  return { exportDoc, ready };
})();
